language: python
python:
  - "2.7"
  - "3.6"
services:
  - mongodb
before_script:
  - mysql -e 'create database track_usage_test;'
  - psql -c 'create database track_usage_test;' -U postgres
  - pip install coverage pep8 pymongo==3.5.1 sqlalchemy psycopg2 mysqlclient mongoengine
install:
  - pip install -e .
script:
  - pep8 --repeat src/
  - nosetests --with-coverage --cover-package=flask_track_usage --cover-min-percentage=80 -v test/*.py
notifications:
  email: false
addons:
  postgresql: "9.5"
